version: "3.7"

services:
  nginx:
    container_name: nginx-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-nginx-image
    volumes:
      - ./:/var/www/example.com
      - ./my-nginx.conf:/etc/nginx/conf/nginx.conf
      - ./example.com.conf:/etc/nginx/conf.d/example.com.conf
    ports:
      - 8080:80
      - 443:443
    restart: always